export const PATH = {
  HOME: "/",
  ABOUT: "/about",
  AUTH: "/auth",
  LOGIN: "/auth/login",
  SIGN_UP: "/auth/sign-up",
  FORGOT_PASSWORD: "/auth/forgot-password",
  VERIFY_FORGOT_OTP: "/auth/verify-forgot-password-otp",
  RESET_PASSWORD: "/auth/reset-password",
  CART: "/cart",
  TEST: "/test",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/product/:productId",
  PROFILE: "/profile",
  PROFILE_EDIT: "/profile/me",
  VIEWED_PRODUCTS: "/profile/viewed-products",
  CHANGE_PASSWORD: "/profile/change-password",
  FAVORITE: "/profile/favorites",
  ORDER: "/profile/order",
  CHECKOUT: "/checkout",
  OTHER: "/other",
  CONTACT: "/contact",
};

export const PAGE_TITLE = {
  HOME: "pageTitle.home",
  ABOUT: "pageTitle.about",
  SIGN_UP: "pageTitle.signUp",
  LOGIN: "pageTitle.signIn",
  TEST: "pageTitle.test",
  PRODUCT: "pageTitle.product",
  CART: "pageTitle.cart",
  OTHER: "pageTitle.other",
  CONTACT: "pageTitle.contact",
  CHECKOUT: "pageTitle.checkout",
  PRODUCT_DETAIL: "pathTitle.productDetail",
  FORGOT_PASSWORD: "pageTitle.forgot-password",
  VERIFY_FORGOT_OTP: "pageTitle.verify-forgot-password-otp",
  RESET_PASSWORD: "pageTitle.reset-password",

  PROFILE: "pageTitle.profile",
  PROFILE_EDIT: "pageTitle.me",
  VIEWED_PRODUCTS: "pageTitle.viewed-products",
  CHANGE_PASSWORD: "pageTitle.change-password",
  FAVORITE: "pageTitle.favorites",
  ORDER: "pageTitle.order",
};
